// ============================================================
// AutoCart — Demo Seed Data
// Realistic sample data for demo/development. Replace with
// Supabase database data when deploying to production.
// ============================================================

import { AutoCart, User } from './types'

// ─── Demo Users ───────────────────────────────────────────────
export const DEMO_USERS: User[] = [
  {
    id: 'user-001',
    email: 'macromaster@demo.com',
    username: 'macromaster',
    displayName: 'Marco Ramirez',
    bio: 'ISSA Certified Trainer | 10+ years meal prepping | Helping you hit your macros without breaking the bank 💪',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=macromaster',
    isPublic: true,
    userType: 'creator',
    socialLinks: {
      instagram: '@macromaster',
      tiktok: '@macromaster_fit',
      youtube: 'MacroMaster',
    },
    followerCount: 48200,
    followingCount: 312,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2025-03-01T08:00:00Z',
  },
  {
    id: 'user-002',
    email: 'cleaneatsmom@demo.com',
    username: 'cleaneatsmom',
    displayName: 'Jessica Chen',
    bio: 'Mom of 3 | Gluten-free kitchen | Making healthy eating easy for the whole family 🥗',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=cleaneatsmom',
    isPublic: true,
    userType: 'creator',
    socialLinks: {
      instagram: '@cleaneatsmom',
      tiktok: '@cleaneatsmom',
    },
    followerCount: 31500,
    followingCount: 204,
    createdAt: '2024-02-20T09:00:00Z',
    updatedAt: '2025-02-28T12:00:00Z',
  },
  {
    id: 'user-003',
    email: 'shredseason@demo.com',
    username: 'shredseason',
    displayName: 'Tyler Brooks',
    bio: 'Natural bodybuilder | Contest prep specialist | Cutting week carts that actually taste good 🔥',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=shredseason',
    isPublic: true,
    userType: 'creator',
    socialLinks: {
      instagram: '@shredseason',
      youtube: 'ShredSeason',
      tiktok: '@shredseason_fit',
    },
    followerCount: 22800,
    followingCount: 180,
    createdAt: '2024-03-01T11:00:00Z',
    updatedAt: '2025-03-10T09:00:00Z',
  },
  {
    id: 'user-004',
    email: 'dormchef@demo.com',
    username: 'dormchef',
    displayName: 'Alex Kim',
    bio: 'College student | Eating well on $50/week | Budget meal prep tips 🎓',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=dormchef',
    isPublic: true,
    userType: 'creator',
    socialLinks: {
      tiktok: '@dormchef',
      instagram: '@dormchef',
    },
    followerCount: 89400,
    followingCount: 156,
    createdAt: '2024-04-10T14:00:00Z',
    updatedAt: '2025-03-15T10:00:00Z',
  },
  {
    id: 'user-005',
    email: 'wrestlerfuel@demo.com',
    username: 'wrestlerfuel',
    displayName: 'Jake Morrison',
    bio: 'D1 wrestler | Sports dietitian student | High protein, weight-class conscious eating 🤼',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=wrestlerfuel',
    isPublic: true,
    userType: 'creator',
    socialLinks: {
      instagram: '@wrestlerfuel',
      twitter: '@wrestlerfuel',
    },
    followerCount: 14300,
    followingCount: 89,
    createdAt: '2024-05-01T08:00:00Z',
    updatedAt: '2025-02-20T15:00:00Z',
  },
  {
    id: 'user-demo',
    email: 'demo@autocart.app',
    username: 'you',
    displayName: 'Demo User',
    bio: 'Just getting started with AutoCart!',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=demouser',
    isPublic: true,
    userType: 'user',
    createdAt: '2025-03-01T00:00:00Z',
    updatedAt: '2025-03-01T00:00:00Z',
  },
]

// ─── Demo AutoCarts ───────────────────────────────────────────
export const DEMO_CARTS: AutoCart[] = [

  // ── 1. High Protein Budget Meal Prep ──────────────────────
  {
    id: 'cart-001',
    creatorId: 'user-001',
    creator: DEMO_USERS[0],
    title: 'High Protein Budget Meal Prep',
    description: 'My go-to weekly cart for hitting 180g+ protein without spending over $75. Chicken, eggs, and rice are the backbone. Clean, simple, effective. Great for intermediate lifters who want results without overthinking it.',
    coverImage: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80',
    category: 'meal-prep',
    visibility: 'public',
    tags: ['high-protein', 'budget', 'chicken', 'weekly-prep', 'beginner-friendly'],
    dietaryLabels: ['high-protein'],
    prepGoal: 'bulking',
    servings: 20,
    prepDays: 5,
    estimatedTotalCost: 72.40,
    estimatedCostPerMeal: 3.62,
    macrosPerServing: { calories: 545, protein: 48, carbs: 44, fat: 13 },
    items: [
      { id: 'item-001', cartId: 'cart-001', name: 'Chicken Breast', quantity: 5, unit: 'lbs', category: 'protein', estimatedPrice: 4.49, preferredBrand: 'Tyson', acceptableSubstitutions: ['Chicken Thighs', 'Turkey Breast'] },
      { id: 'item-002', cartId: 'cart-001', name: 'Whole Eggs', quantity: 3, unit: 'dozen', category: 'protein', estimatedPrice: 5.99, preferredBrand: "Eggland's Best" },
      { id: 'item-003', cartId: 'cart-001', name: 'White Rice', quantity: 1, unit: '5-lb bag', category: 'grains', estimatedPrice: 3.49, acceptableSubstitutions: ['Brown Rice', 'Jasmine Rice'] },
      { id: 'item-004', cartId: 'cart-001', name: 'Broccoli Florets (Frozen)', quantity: 3, unit: 'lbs', category: 'frozen', estimatedPrice: 2.99 },
      { id: 'item-005', cartId: 'cart-001', name: 'Cottage Cheese', quantity: 2, unit: 'lbs', category: 'dairy', estimatedPrice: 4.49, preferredBrand: 'Good Culture', acceptableSubstitutions: ['Greek Yogurt'] },
      { id: 'item-006', cartId: 'cart-001', name: 'Canned Tuna in Water', quantity: 10, unit: 'count', category: 'pantry', estimatedPrice: 1.29, preferredBrand: 'Starkist' },
      { id: 'item-007', cartId: 'cart-001', name: 'Olive Oil', quantity: 1, unit: 'bottle', category: 'condiments', estimatedPrice: 6.99 },
      { id: 'item-008', cartId: 'cart-001', name: 'Sweet Potatoes', quantity: 3, unit: 'lbs', category: 'produce', estimatedPrice: 3.49 },
      { id: 'item-009', cartId: 'cart-001', name: 'Greek Yogurt (Plain)', quantity: 1, unit: '32-oz tub', category: 'dairy', estimatedPrice: 6.49, preferredBrand: 'Chobani' },
      { id: 'item-010', cartId: 'cart-001', name: 'Black Beans (Canned)', quantity: 4, unit: 'cans', category: 'pantry', estimatedPrice: 1.19 },
      { id: 'item-011', cartId: 'cart-001', name: 'Spinach', quantity: 1, unit: '16-oz bag', category: 'produce', estimatedPrice: 4.49 },
      { id: 'item-012', cartId: 'cart-001', name: 'Protein Powder (Whey)', quantity: 1, unit: 'container', category: 'supplements', estimatedPrice: 29.99, preferredBrand: 'Optimum Nutrition Gold Standard' },
    ],
    meals: [
      {
        id: 'meal-001-1',
        name: 'Breakfast',
        emoji: '🍳',
        description: 'Scrambled eggs with sautéed spinach and roasted sweet potato. High protein, sustained energy to start the day strong.',
        cartItems: ['Whole Eggs', 'Spinach', 'Sweet Potatoes', 'Olive Oil'],
        macros: { calories: 420, protein: 35, carbs: 30, fat: 14 },
        prepTimeMinutes: 15,
        instructions: [
          'Preheat oven to 400°F. Dice sweet potatoes into ½-inch cubes, toss with ½ tsp olive oil and a pinch of salt.',
          'Roast sweet potatoes on a sheet pan for 20–25 minutes, flipping halfway, until golden and fork-tender.',
          'Meanwhile, whisk 3 eggs with a pinch of salt and black pepper in a bowl.',
          'Heat a non-stick skillet over medium heat with a small drizzle of olive oil. Add a handful of spinach and stir 1 minute until wilted.',
          'Pour in eggs and gently scramble with a spatula, pulling the eggs from the edges to the center. Remove from heat while still slightly glossy.',
          'Plate eggs alongside sweet potatoes. Season with hot sauce or salsa if desired.',
        ],
      },
      {
        id: 'meal-001-2',
        name: 'Lunch',
        emoji: '🍗',
        description: 'Baked chicken breast over white rice with steamed broccoli. The classic muscle-building combo — clean, filling, and easy to prep in bulk.',
        cartItems: ['Chicken Breast', 'White Rice', 'Broccoli Florets (Frozen)', 'Olive Oil'],
        macros: { calories: 540, protein: 55, carbs: 48, fat: 9 },
        prepTimeMinutes: 30,
        instructions: [
          'Season chicken breasts with garlic powder, paprika, salt, and pepper. Drizzle with olive oil.',
          'Bake at 400°F for 20–24 minutes until internal temperature reaches 165°F. Let rest 5 minutes before slicing.',
          'Rinse 1 cup white rice per 2 servings. Cook in a rice cooker or pot with 2:1 water ratio — bring to boil, reduce to low, cover 18 minutes.',
          'While rice cooks, microwave frozen broccoli per package (about 5 minutes) or steam in a pot for 4–5 minutes until bright green and tender.',
          'Slice or shred the rested chicken. Divide into meal prep containers: rice on one side, chicken in the center, broccoli on the other side.',
          'Drizzle with a light splash of low-sodium soy sauce or hot sauce before sealing.',
        ],
      },
      {
        id: 'meal-001-3',
        name: 'Dinner',
        emoji: '🥣',
        description: 'High-protein cottage cheese and tuna power bowl with black beans. No cooking needed — perfect for a quick, filling final meal.',
        cartItems: ['Canned Tuna in Water', 'Cottage Cheese', 'Black Beans (Canned)', 'Spinach'],
        macros: { calories: 380, protein: 52, carbs: 24, fat: 6 },
        prepTimeMinutes: 5,
        instructions: [
          'Drain and rinse a can of tuna thoroughly and a half cup of canned black beans.',
          'In a bowl, layer a bed of fresh baby spinach.',
          'Add ½ cup cottage cheese on one side of the bowl.',
          'Flake tuna over the cottage cheese and top with rinsed black beans.',
          'Season with black pepper, a squeeze of lemon juice, and a dash of hot sauce.',
          'Mix gently and eat immediately, or cover and refrigerate for up to 24 hours.',
        ],
      },
    ],
    substitutionRules: [
      { id: 'sub-001', label: 'dairy-free', active: false, replacements: [{ originalItem: 'Cottage Cheese', substituteItem: 'Extra Firm Tofu' }, { originalItem: 'Greek Yogurt (Plain)', substituteItem: 'Coconut Yogurt' }] },
      { id: 'sub-002', label: 'gluten-free', active: false },
    ],
    notes: 'Prep Sunday: Cook all rice in rice cooker (45 min). Bake chicken at 400°F for 22 min. Steam broccoli. Divide into 20 meal prep containers. Refrigerate 5 days, freeze the rest.',
    likesCount: 2847,
    savesCount: 1203,
    viewsCount: 18400,
    createdAt: '2025-01-10T09:00:00Z',
    updatedAt: '2025-03-01T10:00:00Z',
  },

  // ── 2. Bulking Season Cart ────────────────────────────────
  {
    id: 'cart-002',
    creatorId: 'user-001',
    creator: DEMO_USERS[0],
    title: 'Bulking Season Grocery Cart',
    description: "Serious mass-building cart for anyone in a lean bulk. 3500+ calories per day, 220g protein. Not cheap, but worth every penny if you're trying to add real size. Built for a 185lb lifter over 7 days.",
    coverImage: 'https://images.unsplash.com/photo-1607532941433-304659e8198a?w=600&q=80',
    category: 'bulking',
    visibility: 'public',
    tags: ['bulking', 'mass-gain', 'high-calorie', 'powerlifting', 'serious'],
    dietaryLabels: ['high-protein'],
    prepGoal: 'bulking',
    servings: 14,
    prepDays: 7,
    estimatedTotalCost: 124.80,
    estimatedCostPerMeal: 8.91,
    macrosPerServing: { calories: 710, protein: 55, carbs: 78, fat: 22 },
    items: [
      { id: 'item-013', cartId: 'cart-002', name: '93/7 Ground Beef', quantity: 4, unit: 'lbs', category: 'protein', estimatedPrice: 6.99, acceptableSubstitutions: ['85/15 Ground Beef'] },
      { id: 'item-014', cartId: 'cart-002', name: 'Chicken Breast', quantity: 6, unit: 'lbs', category: 'protein', estimatedPrice: 4.49, preferredBrand: 'Tyson' },
      { id: 'item-015', cartId: 'cart-002', name: 'Salmon Fillets', quantity: 2, unit: 'lbs', category: 'protein', estimatedPrice: 11.99 },
      { id: 'item-016', cartId: 'cart-002', name: 'Whole Milk', quantity: 1, unit: 'gallon', category: 'dairy', estimatedPrice: 5.29 },
      { id: 'item-017', cartId: 'cart-002', name: 'Whole Eggs', quantity: 3, unit: 'dozen', category: 'protein', estimatedPrice: 5.99 },
      { id: 'item-018', cartId: 'cart-002', name: 'Jasmine Rice', quantity: 1, unit: '10-lb bag', category: 'grains', estimatedPrice: 7.99 },
      { id: 'item-019', cartId: 'cart-002', name: 'Oats (Rolled)', quantity: 1, unit: '5-lb bag', category: 'grains', estimatedPrice: 5.49, preferredBrand: "Bob's Red Mill" },
      { id: 'item-020', cartId: 'cart-002', name: 'Almond Butter', quantity: 2, unit: 'jars', category: 'pantry', estimatedPrice: 8.99, acceptableSubstitutions: ['Peanut Butter'] },
      { id: 'item-021', cartId: 'cart-002', name: 'Avocados', quantity: 6, unit: 'count', category: 'produce', estimatedPrice: 1.49 },
      { id: 'item-022', cartId: 'cart-002', name: 'Sweet Potatoes', quantity: 5, unit: 'lbs', category: 'produce', estimatedPrice: 3.49 },
      { id: 'item-023', cartId: 'cart-002', name: 'Banana', quantity: 1, unit: 'bunch', category: 'produce', estimatedPrice: 1.89 },
      { id: 'item-024', cartId: 'cart-002', name: 'Mass Gainer Protein', quantity: 1, unit: 'bag', category: 'supplements', estimatedPrice: 44.99, preferredBrand: 'Optimum Nutrition Serious Mass' },
    ],
    meals: [
      {
        id: 'meal-002-1',
        name: 'Pre-Workout Oat Bowl',
        emoji: '🥣',
        description: 'Thick rolled oat bowl with banana, almond butter, and whole milk. Slow-burning carbs and healthy fats for maximum training fuel.',
        cartItems: ['Oats (Rolled)', 'Banana', 'Almond Butter', 'Whole Milk', 'Whole Eggs'],
        macros: { calories: 720, protein: 28, carbs: 88, fat: 26 },
        prepTimeMinutes: 10,
        instructions: [
          'Bring 1¼ cups whole milk to a simmer in a small saucepan over medium heat (or microwave in a bowl for 90 seconds).',
          'Stir in ½ cup rolled oats and a pinch of salt. Cook on medium-low, stirring occasionally, for 5 minutes until thick and creamy.',
          'While oats cook, fry 2 whole eggs sunny-side-up in a lightly oiled skillet over medium-low heat, covering with a lid for 2 minutes.',
          'Transfer oats to a bowl. Slice half a banana over the top and dollop with 2 tablespoons of almond butter.',
          'Lay the eggs alongside the oat bowl or on top for extra protein.',
          'Optional: drizzle with honey or a dash of cinnamon. Eat 45–60 minutes before training.',
        ],
      },
      {
        id: 'meal-002-2',
        name: 'Post-Workout Power Bowl',
        emoji: '🍚',
        description: 'Ground beef and jasmine rice with roasted sweet potato. Timed right after training to spike insulin and drive nutrients into recovering muscles.',
        cartItems: ['93/7 Ground Beef', 'Jasmine Rice', 'Sweet Potatoes', 'Avocados'],
        macros: { calories: 780, protein: 58, carbs: 75, fat: 24 },
        prepTimeMinutes: 35,
        instructions: [
          'Dice sweet potatoes into 1-inch cubes. Toss with a drizzle of oil, salt, pepper, and garlic powder. Spread on a sheet pan and roast at 425°F for 25 minutes, flipping once.',
          'Cook 2 cups jasmine rice in 3 cups water: bring to boil, reduce to lowest heat, cover and cook 15 minutes. Remove from heat and let steam 10 more minutes.',
          'Brown 6 oz ground beef in a skillet over medium-high heat, breaking it up with a spatula. Season with salt, pepper, and onion powder. Cook until no pink remains, about 7 minutes.',
          'Drain any excess fat. Stir in a splash of Worcestershire sauce or coconut aminos for flavor.',
          'Build the bowl: rice base, ground beef on top, sweet potatoes on the side, and sliced avocado.',
          'Consume within 30–60 minutes post-workout for optimal nutrient uptake.',
        ],
      },
      {
        id: 'meal-002-3',
        name: 'Evening Salmon Plate',
        emoji: '🐟',
        description: 'Pan-seared salmon with jasmine rice and avocado. Omega-3s for muscle repair, carbs to replenish glycogen, and healthy fats to keep hormones optimal overnight.',
        cartItems: ['Salmon Fillets', 'Jasmine Rice', 'Avocados'],
        macros: { calories: 640, protein: 48, carbs: 52, fat: 28 },
        prepTimeMinutes: 20,
        instructions: [
          'Pat a 6–8 oz salmon fillet completely dry with paper towels — this is key for a good sear.',
          'Season generously with salt, pepper, garlic powder, and a pinch of paprika on both sides.',
          'Heat a cast-iron or stainless skillet over medium-high heat until very hot. Add a splash of oil.',
          'Place salmon skin-side up and press gently for 10 seconds. Sear 4 minutes without moving.',
          'Flip carefully with a spatula. Cook skin-side down 3–4 more minutes until the skin is crisp and the thickest part flakes easily with a fork.',
          'Plate over a scoop of jasmine rice with half a sliced avocado on the side. Finish with a squeeze of fresh lemon.',
        ],
      },
    ],
    substitutionRules: [
      { id: 'sub-003', label: 'dairy-free', active: false, replacements: [{ originalItem: 'Whole Milk', substituteItem: 'Oat Milk (Full Fat)' }] },
    ],
    notes: 'The key to a lean bulk is consistent eating — 3 main meals + 2-3 snacks daily. Prep in two batches mid-week. Use the mass gainer shake between meals if struggling to hit calorie targets.',
    likesCount: 1924,
    savesCount: 876,
    viewsCount: 12300,
    createdAt: '2025-01-22T11:00:00Z',
    updatedAt: '2025-02-14T09:00:00Z',
  },

  // ── 3. Gluten-Free Family Prep ────────────────────────────
  {
    id: 'cart-003',
    creatorId: 'user-002',
    creator: DEMO_USERS[1],
    title: 'Gluten-Free Family Meal Prep',
    description: 'Weekly cart for our family of 4 — all gluten-free, kid-approved, and ready in under 2 hours on Sunday. My youngest has celiac so I make sure everything is certified GF. Balanced, colorful, and genuinely delicious.',
    coverImage: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600&q=80',
    category: 'family',
    visibility: 'public',
    tags: ['gluten-free', 'family', 'celiac-safe', 'kid-friendly', 'weekly'],
    dietaryLabels: ['gluten-free', 'dairy-free'],
    prepGoal: 'family-meal-prep',
    servings: 28,
    prepDays: 7,
    estimatedTotalCost: 98.60,
    estimatedCostPerMeal: 3.52,
    macrosPerServing: { calories: 465, protein: 34, carbs: 40, fat: 16 },
    items: [
      { id: 'item-025', cartId: 'cart-003', name: 'Chicken Thighs (Bone-in)', quantity: 4, unit: 'lbs', category: 'protein', estimatedPrice: 3.99 },
      { id: 'item-026', cartId: 'cart-003', name: 'Ground Turkey', quantity: 2, unit: 'lbs', category: 'protein', estimatedPrice: 5.49 },
      { id: 'item-027', cartId: 'cart-003', name: 'Salmon (Wild-caught)', quantity: 1.5, unit: 'lbs', category: 'protein', estimatedPrice: 12.99, preferredBrand: 'Kirkland (Costco)' },
      { id: 'item-028', cartId: 'cart-003', name: 'Brown Rice (GF Certified)', quantity: 1, unit: '5-lb bag', category: 'grains', estimatedPrice: 5.99, preferredBrand: 'Lundberg Organic' },
      { id: 'item-029', cartId: 'cart-003', name: 'GF Pasta', quantity: 2, unit: 'boxes', category: 'grains', estimatedPrice: 3.99, preferredBrand: 'Barilla Gluten Free', acceptableSubstitutions: ['Banza Chickpea Pasta'] },
      { id: 'item-030', cartId: 'cart-003', name: 'Mixed Stir Fry Vegetables', quantity: 2, unit: 'lbs', category: 'produce', estimatedPrice: 4.49 },
      { id: 'item-031', cartId: 'cart-003', name: 'Broccoli', quantity: 2, unit: 'heads', category: 'produce', estimatedPrice: 2.49 },
      { id: 'item-032', cartId: 'cart-003', name: 'Zucchini', quantity: 4, unit: 'count', category: 'produce', estimatedPrice: 0.89 },
      { id: 'item-033', cartId: 'cart-003', name: 'Cherry Tomatoes', quantity: 1, unit: 'pint', category: 'produce', estimatedPrice: 3.99 },
      { id: 'item-034', cartId: 'cart-003', name: 'Coconut Aminos (GF Soy Sauce Alt)', quantity: 1, unit: 'bottle', category: 'condiments', estimatedPrice: 6.99, preferredBrand: 'Bragg' },
      { id: 'item-035', cartId: 'cart-003', name: 'Avocado Oil', quantity: 1, unit: 'bottle', category: 'condiments', estimatedPrice: 7.99 },
      { id: 'item-036', cartId: 'cart-003', name: 'Blueberries', quantity: 2, unit: 'pints', category: 'produce', estimatedPrice: 3.49 },
    ],
    meals: [
      {
        id: 'meal-003-1',
        name: 'GF Chicken Stir-Fry',
        emoji: '🥢',
        description: 'Tender chicken thighs tossed with colorful stir-fry vegetables in coconut aminos over brown rice. Kid-friendly, completely gluten-free, and ready in 25 minutes.',
        cartItems: ['Chicken Thighs (Bone-in)', 'Mixed Stir Fry Vegetables', 'Brown Rice (GF Certified)', 'Coconut Aminos (GF Soy Sauce Alt)', 'Avocado Oil'],
        macros: { calories: 480, protein: 36, carbs: 42, fat: 16 },
        prepTimeMinutes: 25,
        instructions: [
          "Cook brown rice per package instructions (typically 45 minutes) — start this first so it's ready when everything else is done.",
          'If using bone-in thighs, remove bones and skin after cooking to make kid-friendly bites. Or start with boneless: slice into 1-inch strips.',
          'Heat 1 tbsp avocado oil in a large wok or skillet over high heat until shimmering.',
          'Add chicken pieces and cook without stirring for 3 minutes to get a golden crust. Stir and cook another 3–4 minutes until cooked through.',
          'Push chicken to the side. Add stir-fry vegetables and toss in the hot pan for 4–5 minutes until just tender with a slight crisp.',
          'Pour in 2–3 tbsp coconut aminos, toss everything together, and cook 1 more minute.',
          'Serve over brown rice. Optionally top with sesame seeds — verify the brand is GF certified.',
        ],
      },
      {
        id: 'meal-003-2',
        name: 'Turkey & GF Pasta Bake',
        emoji: '🍝',
        description: 'Comforting ground turkey with gluten-free pasta, zucchini, and cherry tomatoes. The whole family loves this — even picky eaters clean their plates.',
        cartItems: ['Ground Turkey', 'GF Pasta', 'Zucchini', 'Cherry Tomatoes', 'Avocado Oil'],
        macros: { calories: 460, protein: 35, carbs: 44, fat: 14 },
        prepTimeMinutes: 30,
        instructions: [
          'Bring a large pot of salted water to boil. Cook GF pasta 1–2 minutes less than package directions (it finishes cooking in the oven). Drain and set aside.',
          'Slice zucchini into half-moons and halve cherry tomatoes.',
          'Brown ground turkey in a large oven-safe skillet over medium-high heat, breaking into small pieces. Season with Italian seasoning, garlic powder, salt, and pepper.',
          'Once turkey is cooked through, add zucchini and cook 3 minutes. Add cherry tomatoes and cook 2 more minutes until they begin to burst.',
          'Add the drained pasta to the skillet and stir to combine. Add a splash of pasta water or broth to loosen.',
          'Transfer to a baking dish if needed. Bake at 375°F for 15 minutes until bubbly and lightly golden.',
          'Portion into containers immediately while warm. Stores well refrigerated for 4–5 days.',
        ],
      },
      {
        id: 'meal-003-3',
        name: 'Salmon & Broccoli Rice Bowl',
        emoji: '🐟',
        description: 'Baked wild-caught salmon with roasted broccoli over certified GF brown rice. Omega-3 rich and the cleanest, most nutritious meal in the rotation.',
        cartItems: ['Salmon (Wild-caught)', 'Broccoli', 'Brown Rice (GF Certified)', 'Avocado Oil'],
        macros: { calories: 455, protein: 38, carbs: 32, fat: 18 },
        prepTimeMinutes: 30,
        instructions: [
          'Preheat oven to 400°F. Line a large sheet pan with parchment paper.',
          'Cut broccoli into uniform florets. Toss with 1 tbsp avocado oil, salt, and pepper. Spread on one half of the pan.',
          'Place salmon fillets on the other half. Brush with a thin layer of avocado oil and season with salt, garlic powder, and a pinch of lemon zest.',
          'Roast everything together for 14–16 minutes, until broccoli edges are crispy and salmon flakes easily at the thickest point.',
          'While salmon roasts, warm pre-cooked brown rice in the microwave with a splash of water for 90 seconds.',
          'Flake salmon into large chunks directly on the rice. Add broccoli on the side.',
          'Finish with a squeeze of fresh lemon and a drizzle of coconut aminos for a savory-bright finish.',
        ],
      },
    ],
    notes: 'All items should be labeled "certified gluten-free" or naturally GF. Double-check the GF pasta brand — some brands cross-contaminate. I always call the manufacturer if in doubt.',
    likesCount: 3102,
    savesCount: 1847,
    viewsCount: 21000,
    createdAt: '2025-02-01T08:00:00Z',
    updatedAt: '2025-03-08T11:00:00Z',
  },

  // ── 4. Cutting Week Essentials ────────────────────────────
  {
    id: 'cart-004',
    creatorId: 'user-003',
    creator: DEMO_USERS[2],
    title: 'Cutting Week Essentials',
    description: "My actual contest prep cart — low calorie, high protein, insanely filling. Built for 12 weeks out. Under 1,800 cal/day, 200g+ protein. No excuses, no cheats — just results. If you can't afford supplements just sub the whey for more chicken.",
    coverImage: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80',
    category: 'cutting',
    visibility: 'public',
    tags: ['cutting', 'contest-prep', 'shred', 'low-calorie', 'high-protein'],
    dietaryLabels: ['high-protein', 'low-carb', 'low-calorie'],
    prepGoal: 'cutting',
    servings: 35,
    prepDays: 7,
    estimatedTotalCost: 84.20,
    estimatedCostPerMeal: 2.41,
    macrosPerServing: { calories: 335, protein: 46, carbs: 16, fat: 6 },
    items: [
      { id: 'item-037', cartId: 'cart-004', name: 'Chicken Breast (Skinless)', quantity: 7, unit: 'lbs', category: 'protein', estimatedPrice: 4.49 },
      { id: 'item-038', cartId: 'cart-004', name: 'Egg Whites (Carton)', quantity: 4, unit: 'cartons', category: 'protein', estimatedPrice: 3.99, preferredBrand: 'AllWhites' },
      { id: 'item-039', cartId: 'cart-004', name: 'Tilapia Fillets', quantity: 2, unit: 'lbs', category: 'protein', estimatedPrice: 5.99 },
      { id: 'item-040', cartId: 'cart-004', name: 'Asparagus', quantity: 2, unit: 'lbs', category: 'produce', estimatedPrice: 3.99 },
      { id: 'item-041', cartId: 'cart-004', name: 'Cucumber', quantity: 3, unit: 'count', category: 'produce', estimatedPrice: 0.79 },
      { id: 'item-042', cartId: 'cart-004', name: 'Spinach (Baby)', quantity: 2, unit: 'bags', category: 'produce', estimatedPrice: 4.49 },
      { id: 'item-043', cartId: 'cart-004', name: 'Bell Peppers', quantity: 6, unit: 'count', category: 'produce', estimatedPrice: 1.29 },
      { id: 'item-044', cartId: 'cart-004', name: 'Non-fat Greek Yogurt', quantity: 1, unit: '32-oz tub', category: 'dairy', estimatedPrice: 6.49 },
      { id: 'item-045', cartId: 'cart-004', name: 'Rice Cakes', quantity: 2, unit: 'bags', category: 'snacks', estimatedPrice: 3.99, preferredBrand: 'Quaker' },
      { id: 'item-046', cartId: 'cart-004', name: 'Whey Isolate Protein', quantity: 1, unit: 'container', category: 'supplements', estimatedPrice: 34.99, preferredBrand: 'Dymatize ISO100' },
    ],
    meals: [
      {
        id: 'meal-004-1',
        name: 'Egg White Scramble',
        emoji: '🥚',
        description: 'Fluffy egg white scramble loaded with spinach, bell peppers, and cucumber. Under 250 calories, 38g protein — the leanest breakfast you can make.',
        cartItems: ['Egg Whites (Carton)', 'Spinach (Baby)', 'Bell Peppers', 'Cucumber'],
        macros: { calories: 245, protein: 38, carbs: 12, fat: 3 },
        prepTimeMinutes: 10,
        instructions: [
          'Dice half a bell pepper into small pieces. Slice a quarter cucumber into thin rounds — set aside for after cooking.',
          'Heat a non-stick skillet over medium heat coated with cooking spray (zero calories).',
          'Add bell pepper pieces and cook for 2 minutes until slightly softened.',
          'Add a large handful of baby spinach and stir until wilted, about 1 minute.',
          'Pour in ¾ cup (about 6 oz) of liquid egg whites from the carton. Let sit 30 seconds, then gently fold with a spatula from the edges in.',
          "Remove from heat while still just slightly wet — they'll finish cooking from residual heat.",
          'Top with cucumber slices for freshness and a big dash of hot sauce or red pepper flakes.',
        ],
      },
      {
        id: 'meal-004-2',
        name: 'Shredded Chicken Bowl',
        emoji: '🍗',
        description: 'Shredded chicken breast over a bed of baby spinach with roasted asparagus and rice cakes on the side. High satiety, maximum protein, zero guilt.',
        cartItems: ['Chicken Breast (Skinless)', 'Spinach (Baby)', 'Asparagus', 'Rice Cakes'],
        macros: { calories: 340, protein: 52, carbs: 18, fat: 5 },
        prepTimeMinutes: 30,
        instructions: [
          'Place chicken breasts in a pot and cover with cold water. Add a pinch of salt and any aromatics (garlic clove, bay leaf).',
          'Bring to a boil, then reduce heat to a gentle simmer. Cook 15–18 minutes until internal temp hits 165°F.',
          'Remove chicken and let rest 5 minutes. Shred using two forks, pulling along the grain.',
          'Snap asparagus at the natural breaking point. Season with salt and pepper. Roast or air-fry at 400°F for 10–12 minutes until tips are crispy.',
          'Build the bowl: a large base of baby spinach, shredded chicken piled high, asparagus on the side.',
          'Season with mustard, lemon juice, or calorie-free seasoning blends (Mrs. Dash).',
          'Serve with 2 plain rice cakes on the side for a low-calorie carb source.',
        ],
      },
      {
        id: 'meal-004-3',
        name: 'Tilapia Dinner Plate',
        emoji: '🐠',
        description: 'Lemon-herb tilapia with roasted asparagus and non-fat Greek yogurt dip. Ultra-lean protein to end the day — keeps you full without spiking calories before sleep.',
        cartItems: ['Tilapia Fillets', 'Asparagus', 'Non-fat Greek Yogurt', 'Spinach (Baby)'],
        macros: { calories: 295, protein: 48, carbs: 10, fat: 6 },
        prepTimeMinutes: 20,
        instructions: [
          'Preheat oven to 400°F. Pat tilapia fillets completely dry.',
          'Season fillets with lemon pepper, garlic powder, dried dill, and a pinch of cayenne.',
          'Place fillets on a parchment-lined sheet pan. Lay asparagus spears alongside the fish.',
          'Roast for 12–15 minutes until tilapia flakes when pressed with a fork and asparagus is tender.',
          'While everything roasts, mix ½ cup non-fat Greek yogurt with a pinch of garlic powder, lemon zest, and fresh dill — this is your dipping sauce.',
          'Plate tilapia and asparagus over a handful of baby spinach (the heat will slightly wilt it).',
          'Serve with the yogurt dip on the side. Track every gram — this meal sits right at the calorie target.',
        ],
      },
    ],
    substitutionRules: [
      { id: 'sub-004', label: 'dairy-free', active: false, replacements: [{ originalItem: 'Non-fat Greek Yogurt', substituteItem: 'Plain Coconut Yogurt (Low Cal)' }] },
    ],
    notes: 'Season everything with hot sauce, mustard, or calorie-free seasonings. Track every gram. Meal 6 should always be the protein shake + rice cakes as your last food 2 hours before bed.',
    likesCount: 4218,
    savesCount: 2341,
    viewsCount: 35600,
    createdAt: '2025-01-28T07:00:00Z',
    updatedAt: '2025-03-12T08:00:00Z',
  },

  // ── 5. Cheap College Meal Prep ────────────────────────────
  {
    id: 'cart-005',
    creatorId: 'user-004',
    creator: DEMO_USERS[3],
    title: 'Cheap College Meal Prep ($50 Week)',
    description: "Made for broke college students who still want to eat real food. $50 for the whole week, 3 meals a day, 21 meals total. I eat this every week and I've been lifting for 2 years. Stop buying dining hall food.",
    coverImage: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=600&q=80',
    category: 'college',
    visibility: 'public',
    tags: ['budget', 'college', 'cheap', 'easy', 'beginner', '$50-week'],
    dietaryLabels: ['high-protein'],
    prepGoal: 'budget',
    servings: 21,
    prepDays: 7,
    estimatedTotalCost: 48.50,
    estimatedCostPerMeal: 2.31,
    macrosPerServing: { calories: 570, protein: 30, carbs: 68, fat: 15 },
    items: [
      { id: 'item-047', cartId: 'cart-005', name: 'Chicken Leg Quarters', quantity: 5, unit: 'lbs', category: 'protein', estimatedPrice: 1.49 },
      { id: 'item-048', cartId: 'cart-005', name: 'Eggs (Large)', quantity: 1, unit: '18-ct carton', category: 'protein', estimatedPrice: 3.99 },
      { id: 'item-049', cartId: 'cart-005', name: 'White Rice (5 lb bag)', quantity: 1, unit: 'bag', category: 'grains', estimatedPrice: 3.49 },
      { id: 'item-050', cartId: 'cart-005', name: 'Canned Chickpeas', quantity: 4, unit: 'cans', category: 'pantry', estimatedPrice: 0.99 },
      { id: 'item-051', cartId: 'cart-005', name: 'Canned Diced Tomatoes', quantity: 4, unit: 'cans', category: 'pantry', estimatedPrice: 0.89 },
      { id: 'item-052', cartId: 'cart-005', name: 'Peanut Butter', quantity: 1, unit: 'jar', category: 'pantry', estimatedPrice: 3.49, acceptableSubstitutions: ['Almond Butter'] },
      { id: 'item-053', cartId: 'cart-005', name: 'Bread (Whole Wheat)', quantity: 1, unit: 'loaf', category: 'grains', estimatedPrice: 2.99 },
      { id: 'item-054', cartId: 'cart-005', name: 'Frozen Mixed Vegetables', quantity: 2, unit: 'bags', category: 'frozen', estimatedPrice: 2.49 },
      { id: 'item-055', cartId: 'cart-005', name: 'Bananas', quantity: 1, unit: 'bunch', category: 'produce', estimatedPrice: 1.29 },
      { id: 'item-056', cartId: 'cart-005', name: 'Milk (1 gallon)', quantity: 1, unit: 'gallon', category: 'dairy', estimatedPrice: 4.29 },
      { id: 'item-057', cartId: 'cart-005', name: 'Hot Sauce', quantity: 1, unit: 'bottle', category: 'condiments', estimatedPrice: 2.99 },
    ],
    meals: [
      {
        id: 'meal-005-1',
        name: 'PB Banana Breakfast',
        emoji: '🍌',
        description: 'Peanut butter toast with a banana and a glass of milk. Costs less than $1, takes 3 minutes, and keeps you full until lunch. No excuse to skip breakfast.',
        cartItems: ['Bread (Whole Wheat)', 'Peanut Butter', 'Bananas', 'Milk (1 gallon)'],
        macros: { calories: 520, protein: 22, carbs: 72, fat: 18 },
        prepTimeMinutes: 3,
        instructions: [
          'Toast 2 slices of whole wheat bread in a toaster or toaster oven until golden brown.',
          'Spread 1 full tablespoon of peanut butter on each slice — don\'t be stingy, that\'s where your protein and fat come from.',
          'Slice one banana and layer the rounds on top of the peanut butter.',
          'Pour a large glass (1 cup) of cold whole milk.',
          'Eat immediately. Total prep time: under 3 minutes.',
          'Tip: buy the biggest jar of peanut butter — price per ounce drops significantly.',
        ],
      },
      {
        id: 'meal-005-2',
        name: 'Baked Chicken & Rice',
        emoji: '🍗',
        description: 'Oven-baked chicken leg quarters with white rice and frozen mixed vegetables. The cheapest protein-per-dollar meal you can make — and it actually tastes good.',
        cartItems: ['Chicken Leg Quarters', 'White Rice (5 lb bag)', 'Frozen Mixed Vegetables', 'Hot Sauce'],
        macros: { calories: 610, protein: 42, carbs: 58, fat: 18 },
        prepTimeMinutes: 45,
        instructions: [
          'Preheat oven to 425°F. Pat chicken leg quarters dry with a paper towel.',
          'Season both sides with salt, pepper, garlic powder, and paprika. Line a baking sheet with foil (easy cleanup).',
          'Bake skin-side up for 35–40 minutes until the skin is golden and crispy, and the thickest part of the thigh reads 165°F.',
          'While chicken bakes, rinse 1 cup of rice per 2 servings. Cook using 2:1 water ratio: boil, reduce to low, cover 18 minutes, rest 5 minutes.',
          'Microwave frozen mixed vegetables per bag instructions (about 4–5 minutes) — or toss them in the oven with the chicken for the last 10 minutes.',
          'Plate: a big scoop of rice, chicken leg quarter on top, veggies on the side. Douse everything in hot sauce.',
          'Batch-cook 5–10 quarters at once. Refrigerate cooked chicken up to 4 days.',
        ],
      },
      {
        id: 'meal-005-3',
        name: 'Chickpea Tomato Stew',
        emoji: '🫘',
        description: 'Hearty one-pot chickpea and tomato stew over white rice. Vegan-friendly, incredibly cheap, and way better than it sounds. High fiber keeps you full for hours.',
        cartItems: ['Canned Chickpeas', 'Canned Diced Tomatoes', 'White Rice (5 lb bag)', 'Eggs (Large)'],
        macros: { calories: 560, protein: 26, carbs: 80, fat: 10 },
        prepTimeMinutes: 20,
        instructions: [
          'Drain and rinse 1 can of chickpeas. Open 1 can of diced tomatoes (do not drain — the juice is your base).',
          'Add both to a small saucepan over medium heat. Season with cumin, paprika, salt, pepper, and a pinch of red chili flakes.',
          'Simmer uncovered for 10–12 minutes, stirring occasionally, until the sauce thickens and coats the chickpeas.',
          'Optionally: crack 1–2 eggs directly into the simmering stew, cover, and cook 4 minutes for a shakshuka-style protein boost.',
          'Serve over a cup of white rice. Add hot sauce and a squeeze of lemon if you have it.',
          'This stew gets better the next day — make a double batch and refrigerate for easy lunch.',
        ],
      },
    ],
    notes: 'Shop at Aldi or Walmart for best prices. Buy in bulk where possible. Chicken leg quarters are the cheapest protein per pound — just bake them at 425°F for 35 minutes.',
    likesCount: 8924,
    savesCount: 5621,
    viewsCount: 78400,
    createdAt: '2025-02-12T15:00:00Z',
    updatedAt: '2025-03-14T09:00:00Z',
  },

  // ── 6. Wrestler High Protein Cart ─────────────────────────
  {
    id: 'cart-006',
    creatorId: 'user-005',
    creator: DEMO_USERS[4],
    title: 'Wrestler High Protein Cart',
    description: 'Designed for wrestlers and combat sports athletes. High protein, moderate carb, timed around training. Built for a 170lb athlete cutting to 165. Lots of lean protein sources, complex carbs pre-workout, low-fat options to make weight.',
    coverImage: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&q=80',
    category: 'athlete',
    visibility: 'public',
    tags: ['wrestling', 'combat-sports', 'weight-class', 'high-protein', 'athlete'],
    dietaryLabels: ['high-protein', 'low-carb'],
    prepGoal: 'cutting',
    servings: 21,
    prepDays: 7,
    estimatedTotalCost: 91.30,
    estimatedCostPerMeal: 4.35,
    macrosPerServing: { calories: 415, protein: 52, carbs: 24, fat: 10 },
    items: [
      { id: 'item-058', cartId: 'cart-006', name: 'Turkey Breast (Deli Thin-Sliced)', quantity: 2, unit: 'lbs', category: 'protein', estimatedPrice: 6.99 },
      { id: 'item-059', cartId: 'cart-006', name: 'Chicken Breast', quantity: 5, unit: 'lbs', category: 'protein', estimatedPrice: 4.49 },
      { id: 'item-060', cartId: 'cart-006', name: 'Egg Whites', quantity: 3, unit: 'cartons', category: 'protein', estimatedPrice: 3.99 },
      { id: 'item-061', cartId: 'cart-006', name: 'Canned Salmon', quantity: 6, unit: 'cans', category: 'protein', estimatedPrice: 3.49, preferredBrand: 'Wild Planet' },
      { id: 'item-062', cartId: 'cart-006', name: 'Greek Yogurt (Non-fat)', quantity: 1, unit: '32-oz tub', category: 'dairy', estimatedPrice: 6.49 },
      { id: 'item-063', cartId: 'cart-006', name: 'Sweet Potatoes', quantity: 4, unit: 'lbs', category: 'produce', estimatedPrice: 3.49 },
      { id: 'item-064', cartId: 'cart-006', name: 'Oatmeal (Instant)', quantity: 1, unit: 'box', category: 'grains', estimatedPrice: 4.49 },
      { id: 'item-065', cartId: 'cart-006', name: 'Asparagus', quantity: 2, unit: 'bunches', category: 'produce', estimatedPrice: 3.99 },
      { id: 'item-066', cartId: 'cart-006', name: 'Whey Protein Isolate', quantity: 1, unit: 'container', category: 'supplements', estimatedPrice: 34.99 },
    ],
    meals: [
      {
        id: 'meal-006-1',
        name: 'Pre-Workout Oatmeal',
        emoji: '🥣',
        description: 'Instant oatmeal cooked with egg whites for a protein boost, topped with Greek yogurt. Steady-release carbs to fuel a full practice without feeling heavy.',
        cartItems: ['Oatmeal (Instant)', 'Egg Whites', 'Greek Yogurt (Non-fat)'],
        macros: { calories: 380, protein: 40, carbs: 42, fat: 4 },
        prepTimeMinutes: 8,
        instructions: [
          'Cook one packet (or ½ cup) of instant oatmeal in 1 cup of water in the microwave for 2 minutes.',
          'Let oatmeal cool for 1 minute — it should be thick but still pourable. This is important: adding egg whites to boiling oats will scramble them.',
          'Stir in ¼ cup of liquid egg whites vigorously and immediately. The residual heat will cook the whites into the oats, creating a creamy, protein-dense base.',
          'Top with a large scoop (½ cup) of non-fat Greek yogurt.',
          'Season with cinnamon and a small drizzle of honey if within your carb budget.',
          'Eat 60–90 minutes before practice. Avoid eating closer than that to prevent stomach discomfort during mat work.',
        ],
      },
      {
        id: 'meal-006-2',
        name: 'Post-Practice Recovery Plate',
        emoji: '🍗',
        description: 'Sliced chicken breast with roasted sweet potato and asparagus. Timed within 30 minutes of finishing practice to accelerate glycogen replenishment and muscle repair.',
        cartItems: ['Chicken Breast', 'Sweet Potatoes', 'Asparagus'],
        macros: { calories: 445, protein: 55, carbs: 32, fat: 8 },
        prepTimeMinutes: 35,
        instructions: [
          'Cube sweet potatoes into 1-inch pieces. Toss with a light spray of cooking oil, salt, and cinnamon or paprika.',
          'Spread on a sheet pan and roast at 400°F for 25 minutes until edges are caramelized.',
          'Season chicken breasts with salt, pepper, and garlic powder. Bake at 400°F for 20–22 minutes, resting 5 minutes before slicing.',
          'Toss asparagus with cooking spray and roast on the same pan as sweet potatoes for the last 12 minutes.',
          'Slice chicken thinly against the grain. Plate alongside sweet potato and asparagus.',
          'Add a dollop of Greek yogurt as a sauce — mix it with a pinch of garlic powder for a savory twist.',
          'If cutting hard the week before a match, reduce sweet potato portion by half and add more asparagus.',
        ],
      },
      {
        id: 'meal-006-3',
        name: 'High-Protein Salmon Wrap',
        emoji: '🥙',
        description: 'Canned wild salmon with Greek yogurt and turkey breast — a quick, dense protein hit before bed. No cooking required, high in casein-style protein to feed muscles overnight.',
        cartItems: ['Canned Salmon', 'Turkey Breast (Deli Thin-Sliced)', 'Greek Yogurt (Non-fat)', 'Asparagus'],
        macros: { calories: 340, protein: 56, carbs: 8, fat: 10 },
        prepTimeMinutes: 5,
        instructions: [
          'Drain a can of wild salmon and flake into a bowl, removing any bones (the soft ones are edible and high in calcium).',
          'Mix salmon with 2 tbsp non-fat Greek yogurt, a squeeze of lemon juice, black pepper, and dried dill.',
          'Lay 3–4 slices of deli turkey breast flat on a plate or cutting board.',
          'Spoon the salmon mixture onto the center of each turkey slice.',
          'Roll tightly into bite-sized wraps. Secure with a toothpick if needed.',
          'Eat with cold asparagus spears on the side (pre-roasted earlier in the week and kept in the fridge).',
          'Consume 1–2 hours before bed. Avoid this meal entirely on hard cutting days before weigh-in.',
        ],
      },
    ],
    notes: 'Pre-workout meal: oatmeal + egg whites. Post-workout: protein shake + sweet potato. Evening: chicken or turkey + asparagus. Cut carbs 2 days before weigh-in.',
    likesCount: 1643,
    savesCount: 921,
    viewsCount: 11200,
    createdAt: '2025-02-20T10:00:00Z',
    updatedAt: '2025-03-05T14:00:00Z',
  },
]

// ─── Favorites (demo logged-in user's saved carts) ────────────
export const DEMO_FAVORITES = [
  { id: 'fav-001', userId: 'user-demo', cartId: 'cart-001', createdAt: '2025-03-10T09:00:00Z' },
  { id: 'fav-002', userId: 'user-demo', cartId: 'cart-005', createdAt: '2025-03-12T15:00:00Z' },
]

// ─── Helpers ──────────────────────────────────────────────────
export function getCartById(id: string): AutoCart | undefined {
  return DEMO_CARTS.find(cart => cart.id === id)
}

export function getUserById(id: string): User | undefined {
  return DEMO_USERS.find(user => user.id === id)
}

export function getCartsByCreator(creatorId: string): AutoCart[] {
  return DEMO_CARTS.filter(cart => cart.creatorId === creatorId && cart.visibility === 'public')
}

export function searchCarts(query: string): AutoCart[] {
  const q = query.toLowerCase()
  return DEMO_CARTS.filter(cart =>
    cart.title.toLowerCase().includes(q) ||
    cart.description.toLowerCase().includes(q) ||
    cart.tags.some(t => t.includes(q)) ||
    cart.creator?.username.includes(q) ||
    cart.creator?.displayName.toLowerCase().includes(q)
  )
}
